# For kubernetes version 18 and 19 (beta snaps)
# This is a sample manifest for creating snapshotclass with IsiPath other than default
# pvc is created with sc which has some different IsiPath e.g. /ifs/custom
# to create a snapshot for this pvc volumesnapshotclass must also be initilized with same IsiPath (i.e. /ifs/custom ) to work snapshot feature
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: "isilon-snapclass-custom"
driver: csi-isilon.dellemc.com
#The deletionPolicy of a volume snapshot class can either be Retain or Delete
#If the deletionPolicy is Delete, then the underlying storage snapshot will be deleted along with the VolumeSnapshotContent object.
#If the deletionPolicy is Retain, then both the underlying snapshot and VolumeSnapshotContent remain
deletionPolicy: Delete
parameters:
#IsiPath should match with respective storageClass IsiPath
  IsiPath: "/ifs/custom"
