isilonClusters:
  - clusterName: "cluster1"         # logical name of PowerScale Cluster
    username: "user"                # username for connecting to PowerScale OneFS API server
    password: "password"            # password for connecting to PowerScale OneFS API server
    endpoint: "1.2.3.4"             # HTTPS endpoint of the PowerScale OneFS API server
    isDefault: true                 # default cluster (would be used by storage classes without ClusterName parameter)
    skipCertificateValidation: true # indicates if client side validation of server's SSL certificate can be skipped
    isiPath: "/ifs/data/csi"        # base path for the volume(directory) to be created on PowerScale

  - clusterName: "cluster2"
    username: "user"
    password: "password"
    endpoint: "1.2.3.4"
    isiPort: "8080"

logLevel: "debug" # CSI log level; valid log levels- "error", "warn"/"warning", "info", "debug"
